### ISSUE TITLE
eclipse 2021-12 JDK17  Open Windowbuilder not display

### ISSUE THREAD

**Issue by yhld456** [eclipse/windowbuilder#122]

**Comment by System0x40** [comment]
@yhld456 Add --illegal-access=permit to the vmargs in your eclipse.ini if its not already there

**Comment by yhld456** [comment]
![win](https://user-images.githubusercontent.com/16898080/145736306-34aa2c92-9b5f-488c-bddb-f38ed99f8a87.png)
![win2](https://user-images.githubusercontent.com/16898080/145736405-2696bd80-d377-48c2-8dc8-b1d981e85abf.png)

!ENTRY org.eclipse.ui 4 0 2021-12-13 08:38:26.067
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
	at org.eclipse.wb.core.model.broadcast.BroadcastSupport.getListener(BroadcastSupport.java:198)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.<init>(JavaInfoParser.java:216)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.<init>(JavaInfoParser.java:208)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.parse(JavaInfoParser.java:150)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF(DesignPage.java:534)
	at org.eclipse.wb.internal.core.editor.DesignPage.access$9(DesignPage.java:522)
	at org.eclipse.wb.internal.core.editor.DesignPage$8$1.run(DesignPage.java:449)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4779)
	at org.eclipse.wb.internal.core.editor.DesignPage$8.run(DesignPage.java:446)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF_withProgress(DesignPage.java:465)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF(DesignPage.java:415)
	at org.eclipse.wb.internal.core.editor.UndoManager.refreshDesignerEditor(UndoManager.java:381)
	at org.eclipse.wb.internal.core.editor.UndoManager.activate(UndoManager.java:90)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState_True(DesignPage.java:263)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState(DesignPage.java:241)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode.showPage(DefaultMultiMode.java:125)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode$1.widgetSelected(DefaultMultiMode.java:63)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1882)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.ui 4 0 2021-12-13 08:38:26.121
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.viewers.ISelectionProvider.addSelectionChangedListener(org.eclipse.jface.viewers.ISelectionChangedListener)" because "this.m_selectionProvider" is null
	at org.eclipse.wb.internal.core.editor.UndoManager.addSelectionListener(UndoManager.java:187)
	at org.eclipse.wb.internal.core.editor.UndoManager.refreshDesignerEditor(UndoManager.java:382)
	at org.eclipse.wb.internal.core.editor.UndoManager.activate(UndoManager.java:90)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState_True(DesignPage.java:263)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState(DesignPage.java:241)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode.showPage(DefaultMultiMode.java:125)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode$1.widgetSelected(DefaultMultiMode.java:63)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1882)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.equinox.p2.repository 2 0 2021-12-13 08:38:34.619

**Comment by System0x40** [comment]
cglib is a code generation library WB uses. WB ships it under org.eclipse.wb.runtime.lib. You either dont have this bundle or it doesnt get loaded. You can start by checking if it exists at all. It should be in your plugins' folder (Keep in mind that Eclipse installer keeps the p2 pool somewhere in user.home by default so the real deal should be there and not in eclipse's installation path)

**Comment by lcaron** [comment]
Hi

The argument --illegal-access=permit is no longer supported with Java 17.

The current snapshot release (https://download.eclipse.org/windowbuilder/lastgoodbuild/) should solve this problem. Did you try with this version ?

**Comment by vogella** [comment]
If i start WB from an runtime Eclipse with a Java 17 runtime and try to open a view I get a JVM crash

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f15eb4b0c76, pid=10865, tid=10870
#
# JRE version: OpenJDK Runtime Environment Temurin-17+35 (17.0+35) (build 17+35)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17+35 (17+35, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpixman-1.so.0+0x8dc76]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/vogella/dev/eclipse-2021-11-10/eclipse/core.10865)
#
# An error report file with more information is saved as:
# /home/vogella/dev/eclipse-2021-11-10/eclipse/hs_err_pid10865.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by System0x40** [comment]
> The current snapshot release (https://download.eclipse.org/windowbuilder/lastgoodbuild/) should solve this problem. Did you try with this version ?

I did. 1.9.7.202112211354 works. It's on Windows tho.
(Temurin 17+35)

**Comment by HipotenusaBR** [comment]
This isn't the solution but this can be helpful for people like me that spent 6 hours for this. I tested running eclipse with JDK 11, and it worked, JDK 17 & 16 don't work. Create a Java 11 project and be happy :) 

remebering: WindowBuilder won't work if the project is 12 or more if the eclipse is running under 11, i don't know how to help if you can't downgrade

i'm also using the pre version

sorry for my english

**Comment by echavez-eb** [comment]
> Hi
> 
> The argument --illegal-access=permit is no longer supported with Java 17.
> 
> The current snapshot release (https://download.eclipse.org/windowbuilder/lastgoodbuild/) should solve this problem. Did you try with this version ?

Using that causes the following errors:
An error occurred while collecting items to be installed
session context was:(profile=C__Program Files_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.wb.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.doc.user.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.rcp.SWT_AWT,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.rcp.SWT_AWT_support,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.rcp.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.rcp.doc.user.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.FormLayout,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.FormLayout.lib,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.MigLayout,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.MigLayout.lib,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.databinding,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.swing.doc.user.feature,1.9.7.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.swing.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.java6,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.jsr296,1.9.1.202112211354

**Comment by lcaron** [comment]
Can you please try with a brand new installation ?

I've successfully installed Eclipse + WB with JDK 17 (Oracle) on my Windows 10 computer

a) I've downloaded and installed Eclipse 2021-12 for commiter
b) I've changed my configuration in order to make Eclipse works with JDK 17
c) I've checked if the installed JRE in Eclipse (Window > Preferences > Java > Installed JRE). It should be JDK 17
d) I opened https://www.eclipse.org/windowbuilder/download.php
d) I dragged & dropped the "install" button located on the line "upcoming"

**Comment by yhld456** [comment]
Thank you, after I use it, the function is normal

**Comment by yhld456** [comment]
> 



> Can you please try with a brand new installation ?
> 
> I've successfully installed Eclipse + WB with JDK 17 (Oracle) on my Windows 10 computer
> 
> a) I've downloaded and installed Eclipse 2021-12 for commiter b) I've changed my configuration in order to make Eclipse works with JDK 17 c) I've checked if the installed JRE in Eclipse (Window > Preferences > Java > Installed JRE). It should be JDK 17 d) I opened https://www.eclipse.org/windowbuilder/download.php d) I dragged & dropped the "install" button located on the line "upcoming"

Thank you, after I use it, the function is normal

**Comment by yhld456** [comment]
Thank you, after I use it, the function is normal


***@***.***
 
From: echavez-eb
Date: 2022-01-09 13:05
To: eclipse/windowbuilder
CC: OrganicVegetables; Mention
Subject: Re: [eclipse/windowbuilder] eclipse 2021-12 JDK17 Open Windowbuilder not display (Issue #122)
Hi
The argument --illegal-access=permit is no longer supported with Java 17.
The current snapshot release (https://download.eclipse.org/windowbuilder/lastgoodbuild/) should solve this problem. Did you try with this version ?
Using that causes the following errors:
An error occurred while collecting items to be installed
session context was:(profile=C__Program Files_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.wb.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.doc.user.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.rcp.SWT_AWT,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.rcp.SWT_AWT_support,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.rcp.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.rcp.doc.user.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.FormLayout,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.FormLayout.lib,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.MigLayout,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.MigLayout.lib,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.databinding,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.doc.user,1.9.1.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.swing.doc.user.feature,1.9.7.202112211354
No repository found containing: org.eclipse.update.feature,org.eclipse.wb.swing.feature,1.9.7.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.java6,1.9.1.202112211354
No repository found containing: osgi.bundle,org.eclipse.wb.swing.jsr296,1.9.1.202112211354
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
