### ISSUE TITLE
WindowBuilder empty palette Java 17 installed in RCP

### ISSUE THREAD

**Issue by Bio7** [eclipse/windowbuilder#134]
I still get an empty palette with Java 17 when I install the latest WindowBuilder plugin in my RCP application with the p2 Update Manager. In Eclipse however it seems to work. The following error is thrown when I open and click on the design tab:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.wb.core.model.ObjectInfo.getBroadcastObject()" because "this.this$0.m_rootObject" is null
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$5.run(ComponentsTreePage.java:157)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runLog(ExecutionUtils.java:106)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.selectGraphicalViewer(ComponentsTreePage.java:148)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$1.selectionChanged(ComponentsTreePage.java:119)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:202)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.deselectAll(AbstractEditPartViewer.java:325)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.handleButtonDown(SelectionTool.java:139)
	at org.eclipse.wb.gef.core.tools.Tool.mouseDown(Tool.java:385)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseDown(SelectionTool.java:238)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseDown(EditDomain.java:244)
	at org.eclipse.wb.internal.gef.tree.TreeEventManager.mouseDown(TreeEventManager.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy9/jdk.proxy9.$Proxy23.mouseDown(Unknown Source)
```

With Java <16 there was no problem.

I can reproduce this error on MacOSX and Windows using
Eclipse Adoptium, java.version: 17.0.1

**Comment by lcaron** [comment]
Hi,

Sorry for that bug... Can you post the whole stacktrace ? 
Can you also check if the plugin **org.eclipse.wb.core** is started ?

**Comment by lcaron** [comment]
In your list of plugins, you have 2 families :
- the plugins with version number 1.9.1.202009181620. These plugins correspond to WB 1.9.4 (https://archive.eclipse.org/windowbuilder/1.9.4/)
- the plugins with version number 1.9.1.202112211354. These plugins correspond to upcoming WB 1.9.8

Can you please clean/update your configuration in order to use only the latest release of WB ?

**Comment by Bio7** [comment]
I once again cleaned up with the latest built (somehow I reverted the installation to test older versions)
However the same error occurs: design tab stays empty,on click the error message -in additon in the console I get a "BurningShell" log message with ASCII Art

Here the updated configuration:

org.eclipse.wb.core (1.10.1.202112211354) "WindowBuilder Core" [Active]
org.eclipse.wb.core.databinding (1.9.1.202112211354) "WindowBuilder Databinding Core" [Active]
org.eclipse.wb.core.databinding.xml (1.9.1.202112211354) "WindowBuilder Databinding XML Core" [Starting]
org.eclipse.wb.core.java (1.9.2.202112211354) "WindowBuilder Core for Java GUI's" [Active]
org.eclipse.wb.core.lib (1.9.1.202112211354) "WindowBuilder Core Libraries" [Active]
org.eclipse.wb.core.ui (1.10.0.202112211354) "WindowBuilder Core UI" [Starting]
org.eclipse.wb.core.xml (1.9.1.202112211354) "WindowBuilder Core for XML GUI's" [Active]
org.eclipse.wb.doc.user (1.9.1.202112211354) "WindowBuilder User Guide" [Starting]
org.eclipse.wb.layout.group (1.9.1.202112211354) "WindowBuilder GroupLayout Support" [Starting]
org.eclipse.wb.os (1.9.1.202112211354) "WindowBuilder Cross-Platform Support" [Active]
org.eclipse.wb.os.macosx (1.9.1.202112211354) "WindowBuilder Mac OS X Support" [Active]
org.eclipse.wb.rcp (1.9.1.202112211354) "SWT Designer" [Active]
org.eclipse.wb.rcp.databinding (1.9.1.202112211354) "SWT Designer Databinding Support" [Active]
org.eclipse.wb.rcp.databinding.emf (1.9.1.202112211354) "SWT Designer Databinding EMF Support" [Starting]
org.eclipse.wb.rcp.databinding.xwt (1.9.1.202112211354) "XWT Databinding Support" [Starting]
org.eclipse.wb.rcp.doc.user (1.9.1.202112211354) "WindowBuilder User Guide - SWT" [Starting]
org.eclipse.wb.rcp.nebula (1.9.1.202112211354) "SWT Designer Nebula Widgets Support" [Active]
org.eclipse.wb.rcp.swing2swt (1.9.1.202112211354) "SWT Designer Swing2SWT Layouts Support" [Starting]
org.eclipse.wb.rcp.SWT_AWT (1.9.1.202112211354) "WindowBuilder SWT_AWT Support" [Starting]
org.eclipse.wb.runtime (1.9.1.202112211354) "WindowBuilder Runtime" [Starting]
org.eclipse.wb.runtime.lib (1.9.1.202112211354) "WindowBuilder Runtime Libraries" [Active]
org.eclipse.wb.swing (1.9.1.202112211354) "Swing Designer" [Active]
org.eclipse.wb.swing.databinding (1.9.1.202112211354) "Swing Designer Databinding Support" [Active]
org.eclipse.wb.swing.doc.user (1.9.1.202112211354) "WindowBuilder User Guide - Swing" [Starting]
org.eclipse.wb.swing.FormLayout (1.9.1.202112211354) "Swing Designer JGoodies FormLayout Support" [Active]
org.eclipse.wb.swing.FormLayout.lib (1.9.1.202112211354) "Swing Designer JGoodies FormLayout Library" [Starting]
org.eclipse.wb.swing.java6 (1.9.1.202112211354) "Swing Designer Java6 Support" [Starting]
org.eclipse.wb.swing.jsr296 (1.9.1.202112211354) "Swing Designer JSR-296 Support" [Starting]
org.eclipse.wb.swing.MigLayout (1.9.1.202112211354) "Swing Designer MigLayout Support" [Starting]
org.eclipse.wb.swing.MigLayout.lib (1.9.1.202112211354) "Swing Designer MigLayout Library" [Starting]
org.eclipse.wb.swt (1.9.1.202112211354) "SWT Designer Core" [Active]

java.lang.NullPointerException: Cannot invoke "org.eclipse.wb.core.model.ObjectInfo.getBroadcastObject()" because "this.this$0.m_rootObject" is null
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$5.run(ComponentsTreePage.java:157)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runLog(ExecutionUtils.java:106)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.selectGraphicalViewer(ComponentsTreePage.java:148)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$1.selectionChanged(ComponentsTreePage.java:119)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:202)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.deselectAll(AbstractEditPartViewer.java:325)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.handleButtonDown(SelectionTool.java:139)
	at org.eclipse.wb.gef.core.tools.Tool.mouseDown(Tool.java:385)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseDown(SelectionTool.java:238)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseDown(EditDomain.java:244)
	at org.eclipse.wb.internal.gef.tree.TreeEventManager.mouseDown(TreeEventManager.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy9/jdk.proxy9.$Proxy22.mouseDown(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at com.eco.bio7.rcp.Application.start(Application.java:16)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
java.lang.NullPointerException: Cannot invoke "org.eclipse.wb.core.model.ObjectInfo.getBroadcastObject()" because "this.this$0.m_rootObject" is null
	at org.eclipse.wb.internal.core.editor.DesignToolbarHelper$5.run(DesignToolbarHelper.java:273)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runLog(ExecutionUtils.java:106)
	at org.eclipse.wb.internal.core.editor.DesignToolbarHelper.refreshSelectionActions(DesignToolbarHelper.java:267)
	at org.eclipse.wb.internal.core.editor.DesignToolbarHelper.refreshDynamicActions(DesignToolbarHelper.java:166)
	at org.eclipse.wb.internal.core.editor.DesignToolbarHelper$3.selectionChanged(DesignToolbarHelper.java:111)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:202)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.setSelection(AbstractEditPartViewer.java:262)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.setSelection(ComponentsTreePage.java:208)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.selectGraphicalViewer(ComponentsTreePage.java:174)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$1.selectionChanged(ComponentsTreePage.java:119)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:202)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.deselectAll(AbstractEditPartViewer.java:325)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.handleButtonDown(SelectionTool.java:139)
	at org.eclipse.wb.gef.core.tools.Tool.mouseDown(Tool.java:385)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseDown(SelectionTool.java:238)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseDown(EditDomain.java:244)
	at org.eclipse.wb.internal.gef.tree.TreeEventManager.mouseDown(TreeEventManager.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy9/jdk.proxy9.$Proxy22.mouseDown(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at com.eco.bio7.rcp.Application.start(Application.java:16)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by lcaron** [comment]
Ok thank you for your feed back.

I'm a bit puzzled by this bug. If you remove the options `--add-options` is it better ?

**Comment by Bio7** [comment]
No, that doesn't makes a difference. I think the bug is quite similar to the reflection bug for Java 16 which was cured for Eclipse with the workaround. 

https://github.com/eclipse/windowbuilder/issues/45

However this also didn't work for an RCP application.

The last running version was with Java 15.

Unfortunately I don't get an informative error message why the design tab is empty.
