### ISSUE TITLE
Illegal argument during drawImage

### ISSUE THREAD

**Issue by MarcelS4** [eclipse/windowbuilder#162]
When placing a widget on the screen the UI displays that the element can not be placed in that location (this is as is expected). However an error is still logged. This would not necessarily be an issue, however this occurs even when the mouse just moves over such a "illegal" position. 

In my case the error can be replicated by adding a ScrollPane widget to a layout and then selecting another widget and dragging it over the ScrollPane. (No need to drop it. The following error will occur)

java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4874)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.SWT.error(SWT.java:4779)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:912)
	at org.eclipse.wb.draw2d.Graphics.drawImage(Graphics.java:262)
	at org.eclipse.wb.internal.draw2d.SemiTransparentFigure.paintClientArea(SemiTransparentFigure.java:59)
	at org.eclipse.wb.draw2d.Figure.paintFigure(Figure.java:533)
	at org.eclipse.wb.draw2d.Figure.paint(Figure.java:514)
	at org.eclipse.wb.draw2d.Figure.paintChildren(Figure.java:552)
	at org.eclipse.wb.draw2d.Figure.paint(Figure.java:516)
	at org.eclipse.wb.draw2d.Figure.paintChildren(Figure.java:552)
	at org.eclipse.wb.draw2d.Figure.paint(Figure.java:516)
	at org.eclipse.wb.internal.draw2d.FigureCanvas.handlePaint(FigureCanvas.java:188)
	at org.eclipse.wb.internal.draw2d.FigureCanvas$3.handleEvent(FigureCanvas.java:150)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1620)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4817)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at de.dsa.prodis.automation.AutomationApplication.start(AutomationApplication.java:357)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)

**Comment by wimjongman** [comment]
Thank you, @MarcelS4.
