### ISSUE TITLE
WindowBuilder unable to load 'super' class

### ISSUE THREAD

**Issue by feujun** [eclipse/windowbuilder#183]
I don't know if I should post this here or somewhere else, so just tell me where I should take my bug-report if I'm wrong here 😃.

### Describe the bug
When opening a UI in the Design-Tab, WindowBuilder fails with "Unable to load 'super' class" error. The complete stacktrace is:

<details>
 <summary>Stacktrace</summary>

```
org.eclipse.wb.internal.core.utils.exception.DesignerException: 109 (Unable to load 'super' class). de.custom.CustomFrame
	at org.eclipse.wb.internal.core.parser.AbstractParseFactory.getSuperClass(AbstractParseFactory.java:387)
	at org.eclipse.wb.internal.swing.parser.ParseFactory.getRootContext(ParseFactory.java:120)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.prepareParseContext(JavaInfoParser.java:1184)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.parse(JavaInfoParser.java:242)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser$1.runObject(JavaInfoParser.java:152)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser$1.runObject(JavaInfoParser.java:1)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:159)
	at org.eclipse.wb.internal.core.parser.JavaInfoParser.parse(JavaInfoParser.java:150)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF(DesignPage.java:534)
	at org.eclipse.wb.internal.core.editor.DesignPage$8$1.run(DesignPage.java:449)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4779)
	at org.eclipse.wb.internal.core.editor.DesignPage$8.run(DesignPage.java:446)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF_withProgress(DesignPage.java:465)
	at org.eclipse.wb.internal.core.editor.DesignPage.internal_refreshGEF(DesignPage.java:415)
	at org.eclipse.wb.internal.core.editor.UndoManager.refreshDesignerEditor(UndoManager.java:381)
	at org.eclipse.wb.internal.core.editor.UndoManager.activate(UndoManager.java:90)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState_True(DesignPage.java:263)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState(DesignPage.java:241)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode.showPage(DefaultMultiMode.java:125)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode$1.widgetSelected(DefaultMultiMode.java:63)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1882)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.ClassNotFoundException: de.custom.CustomFrame
	at org.eclipse.wb.internal.core.utils.reflect.CompositeClassLoader.findClass(CompositeClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.wb.internal.core.parser.AbstractParseFactory.getSuperClass(AbstractParseFactory.java:385)
	... 60 more
```
</details>
I could also post the entire eclipse-Log but there is not much information other than that stacktrace (to be precise: none other)

### To Reproduce
A bit difficult. It needs a 3-Project-Setup and does only occur when using Maven™:
Project 1 (LibProject) is a Standard-Maven-Project. It defines a class `de.custom.CustomFrame` like this:
```java
package de.custom;

import java.awt.Cursor;
import javax.swing.JFrame;

public class CustomFrame extends JFrame{
	public CustomFrame() {
		this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
	}
}
```
With this, you do a `mvn install` and **delete the project from the workspace**.

Project 2 (ParentProject) is a Standard-Maven-Project. It defines _nothing_, but exports its entries in the project-properties via Java Build Path → Order and Export → Check 'Maven Dependencies'.

Project 3 (ChildProject) is _not_ a Maven-Project, but a standard Java-Project. It defines Project 2 (ParentProject) as a Project dependency via Java Build Path → Projects → Add → Parent Project. It has a class `my.custom.frame.MyFrame` like this:
```java
package my.custom.frame;

import java.awt.BorderLayout;
import de.custom.CustomFrame;

public class MyFrame extends CustomFrame {
	public MyFrame() {
		buildFrame();
	}

	private void buildFrame() {
		setLayout(new BorderLayout());
		pack();
		setLocationRelativeTo(null);
		setVisible(true);
	}
}
```
When trying to open above class in the WindowBuilder design tab, the error occurs.

![image](https://user-images.githubusercontent.com/45291670/162917136-c0973be9-c74b-4f2d-8a70-9ba3fdb3a436.png)

I have also exported the projects to a zip, but GitHub won't let me upload it 😢. If you need it, I can try it again later...

### Expected Behaviour
WindowBuilder does not fail and opens the UI. 😃 

### Environment
Operating System: Windows 10 Enterprise 20H2
Eclipse: Version: 2021-12 (4.22.0) (20211202-1639) (I can also recreate the error in 4.20.0.20210612-1200 with WindowBuilder 1.9.7.202202142029)
WindowBuilder: 1.10.0.202203191024
All Projects with Java 8

**Comment by feujun** [comment]
I tried it again on another PC with a fresh install and didn't run into the same problem. So it is unlikely directly a WindowBuilder-problem. I'll look into what is different setup-wise. I'll just close this issue for now...

**Comment by wimjongman** [comment]
Thanks for the feedback. Felix.
