### ISSUE TITLE
Unable to add Cascade item to Menu bar under Linux Mint 

### ISSUE THREAD

**Issue by D14-03** [eclipse/windowbuilder#279]
Note, the issue does **not** present in Eclipse for Windows, don't know about other Linux distros.

To reproduce, create an SWT/JFace Java project, add Application window, Menu bar to that window, and Cascade menu item to that menu bar.

Stack trace looks like following:

Internal Error

WindowBuilder encountered unexpected internal error.

This could be caused by a WindowBuilder bug or by a misconfiguration issue, conflict, partial update, etc.

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "imageHandle" is null

Hide stack trace.
Stack trace:

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "imageHandle" is null
	at org.eclipse.wb.internal.os.linux.OSSupportLinux$Impl64.createImage0(OSSupportLinux.java:663)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux$Impl64.createImage0(OSSupportLinux.java:1)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux.createImage(OSSupportLinux.java:444)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux.getMenuPopupVisualData(OSSupportLinux.java:469)
	at org.eclipse.wb.internal.rcp.support.ToolkitSupportImpl.fetchMenuVisualData(ToolkitSupportImpl.java:92)
	at org.eclipse.wb.internal.swt.support.ToolkitSupport.fetchMenuVisualData(ToolkitSupport.java:99)
	at org.eclipse.wb.internal.swt.model.widgets.menu.MenuInfo.refresh_fetch(MenuInfo.java:164)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.internal.swt.model.widgets.menu.MenuInfo.refresh_fetch(MenuInfo.java:177)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.access$0(ControlInfo.java:1)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo$2.run(ControlInfo.java:127)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:225)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:158)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:124)
	at org.eclipse.wb.internal.swt.model.widgets.ScrollableInfo.refresh_fetch(ScrollableInfo.java:49)
	at org.eclipse.wb.internal.swt.model.widgets.CompositeInfo.refresh_fetch(CompositeInfo.java:305)
	at org.eclipse.wb.core.model.ObjectInfo$6$1.run(ObjectInfo.java:511)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
	at org.eclipse.wb.core.model.ObjectInfo$6.run(ObjectInfo.java:508)
	at org.eclipse.wb.core.model.ObjectInfo.execRefreshOperation(ObjectInfo.java:529)
	at org.eclipse.wb.core.model.ObjectInfo.refresh(ObjectInfo.java:505)
	at org.eclipse.wb.core.model.ObjectInfo.endEdit(ObjectInfo.java:457)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:332)
	at org.eclipse.wb.core.gef.command.EditCommand.execute(EditCommand.java:50)
	at org.eclipse.wb.internal.gef.core.EditDomain.executeCommand(EditDomain.java:59)
	at org.eclipse.wb.gef.core.tools.Tool.executeCommand(Tool.java:209)
	at org.eclipse.wb.gef.core.tools.AbstractCreationTool.handleButtonUp(AbstractCreationTool.java:62)
	at org.eclipse.wb.gef.core.tools.Tool.mouseUp(Tool.java:395)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseUp(EditDomain.java:255)
	at org.eclipse.wb.internal.gef.tree.TreeEventManager.mouseUp(TreeEventManager.java:125)
	at jdk.internal.reflect.GeneratedMethodAccessor255.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy10/jdk.proxy10.$Proxy43.mouseUp(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Full context stack trace:

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "imageHandle" is null
	at org.eclipse.wb.internal.os.linux.OSSupportLinux$Impl64.createImage0(OSSupportLinux.java:663)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux$Impl64.createImage0(OSSupportLinux.java:1)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux.createImage(OSSupportLinux.java:444)
	at org.eclipse.wb.internal.os.linux.OSSupportLinux.getMenuPopupVisualData(OSSupportLinux.java:469)
	at org.eclipse.wb.internal.rcp.support.ToolkitSupportImpl.fetchMenuVisualData(ToolkitSupportImpl.java:92)
	at org.eclipse.wb.internal.swt.support.ToolkitSupport.fetchMenuVisualData(ToolkitSupport.java:99)
	at org.eclipse.wb.internal.swt.model.widgets.menu.MenuInfo.refresh_fetch(MenuInfo.java:164)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.internal.swt.model.widgets.menu.MenuInfo.refresh_fetch(MenuInfo.java:177)
	at org.eclipse.wb.core.model.ObjectInfo.refresh_fetch(ObjectInfo.java:664)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.access$0(ControlInfo.java:1)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo$2.run(ControlInfo.java:127)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:225)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:158)
	at org.eclipse.wb.internal.swt.model.widgets.ControlInfo.refresh_fetch(ControlInfo.java:124)
	at org.eclipse.wb.internal.swt.model.widgets.ScrollableInfo.refresh_fetch(ScrollableInfo.java:49)
	at org.eclipse.wb.internal.swt.model.widgets.CompositeInfo.refresh_fetch(CompositeInfo.java:305)
	at org.eclipse.wb.core.model.ObjectInfo$6$1.run(ObjectInfo.java:511)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
	at org.eclipse.wb.core.model.ObjectInfo$6.run(ObjectInfo.java:508)
	at org.eclipse.wb.core.model.ObjectInfo.execRefreshOperation(ObjectInfo.java:529)
	at org.eclipse.wb.core.model.ObjectInfo.refresh(ObjectInfo.java:505)
	at org.eclipse.wb.core.model.ObjectInfo.endEdit(ObjectInfo.java:457)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:332)
	at org.eclipse.wb.core.gef.command.EditCommand.execute(EditCommand.java:50)
	at org.eclipse.wb.internal.gef.core.EditDomain.executeCommand(EditDomain.java:59)
	at org.eclipse.wb.gef.core.tools.Tool.executeCommand(Tool.java:209)
	at org.eclipse.wb.gef.core.tools.AbstractCreationTool.handleButtonUp(AbstractCreationTool.java:62)
	at org.eclipse.wb.gef.core.tools.Tool.mouseUp(Tool.java:395)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseUp(EditDomain.java:255)
	at org.eclipse.wb.internal.gef.tree.TreeEventManager.mouseUp(TreeEventManager.java:125)
	at jdk.internal.reflect.GeneratedMethodAccessor255.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy10/jdk.proxy10.$Proxy43.mouseUp(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by vogella** [comment]
Could you look into the issue the potentially provide a pull request? The project is more or less run by volunteers at this point.

**Comment by D14-03** [comment]
Yes, potentially. Not at this time though.Just was wondering if there's anything suspecting related.10:45, 21 июня 2022 г., Lars Vogel ***@***.***>:
Could you look into the issue the potentially provide a pull request? The project is more or less run by volunteers at this point.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by ptziegler** [comment]
I've noticed a similar issue and from what I can tell, the problem is that the design viewer neither renders the shell, nor the menu. But in the preview, everything is there. Because there's no menu, there's no handle and thus, a NullPointerException.

![image](https://user-images.githubusercontent.com/70652978/227604652-e24163ab-e64a-4d15-b483-da739b71011e.png)

A search led me to [Bug 570994](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570994), which seems to describe exactly the same behavior. And from what I understand, this is not an Eclipse issue, but rather some weird configuration on my system that's causing those artifacts.

Do we have any GTK experts who might have an idea what's going on here?

GTK Libraries:

> dpkg -l | grep libgtk
ii  libgtk-3-0:amd64                              3.24.33-1ubuntu2                                amd64        GTK graphical user interface library
ii  libgtk-3-bin                                  3.24.33-1ubuntu2                                amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common                               3.24.33-1ubuntu2                                all          common files for the GTK graphical user interface library
ii  libgtk2.0-0:amd64                             2.24.33-2ubuntu2                                amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin                                 2.24.33-2ubuntu2                                amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-common                              2.24.33-2ubuntu2                                all          common files for the GTK graphical user interface library
ii  libgtkmm-3.0-1v5:amd64                        3.24.5-1build1                                  amd64        C++ wrappers for GTK+ (shared libraries)

Cairo Libraries:

> dpkg -l | grep libcairo
ii  libcairo-gobject2:amd64                       1.16.0-5ubuntu2                                 amd64        Cairo 2D vector graphics library (GObject library)
ii  libcairo-gobject2:i386                        1.16.0-5ubuntu2                                 i386         Cairo 2D vector graphics library (GObject library)
ii  libcairo2:amd64                               1.16.0-5ubuntu2                                 amd64        Cairo 2D vector graphics library
ii  libcairo2:i386                                1.16.0-5ubuntu2                                 i386         Cairo 2D vector graphics library
ii  libcairomm-1.0-1v5:amd64                      1.12.2-4build3                                  amd64        C++ wrappers for Cairo (shared libraries)

**Comment by wimjongman** [comment]
Wow!! 🎉🎉Well done. That was hunting us for some time.
