### ISSUE TITLE
IDE setup with installer fails

### ISSUE THREAD

**Issue by col-panic** [eclipse/windowbuilder#324]
Setting up an IDE environment according to https://github.com/eclipse/windowbuilder/blob/master/CONTRIBUTING.md fails on setup with

```
Performing Targlets Modular Target (wb-mvn + Eclipse Platform + Window Builder + Window Builder Website), activate
Repository https://download.eclipse.org/eclipse/updates/4.26-I-builds
Repository https://download.eclipse.org/releases/2022-12
Repository https://download.eclipse.org/cbi/updates/license
Offline = false
Mirrors = true
Include All Platforms = true
-> Window Builder
Include All Requirements = true
Include Binary Equivalents = true
Include Sources = true
Adding repository https://download.eclipse.org/releases/2022-12
Adding repository https://download.eclipse.org/cbi/updates/license
Adding repository https://download.eclipse.org/eclipse/updates/4.26-I-builds
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1664995100989
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: WindowBuilder Tests 1.2.0.v20221005-203818 (org.eclipse.wb.tests 1.2.0.v20221005-203818) requires 'osgi.bundle; org.junit.jupiter.api 5.8.1' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1664995100989
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.wb.tests 0.0.0

Took 7 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by merks** [comment]
The problem is that the setup tries to use the latest and greatest from the platform

![image](https://user-images.githubusercontent.com/208716/194249131-429cd590-48e6-47a0-953b-4ec16d703a63.png)

And it's using the direct-from-maven version of juniper while the plugins.

@wimjongman 

It's probably better to use package imports to avoid this problem.  But I'm running out of time for today...

**Comment by wimjongman** [comment]
I will take a look. Thanks for the pointer.

**Comment by merks** [comment]
@wimjongman  I'll retest again from scratch.

One problem I see now is this error:

![image](https://user-images.githubusercontent.com/208716/194306046-b3eea7bd-5af9-4071-b25a-d7cd73c2cd35.png)

That method was adding during the 2022-09/4.25 release cycle so I think I should fix this and update the *.target to 2022-09...

**Comment by merks** [comment]
I retested from scratch just now and it works for me.

**Comment by wimjongman** [comment]
I also tested it. We are looking forward to the quality patches of @col-panic ;)
