### ISSUE TITLE
Window Builder crashes when doing anything on the Design tab

### ISSUE THREAD

**Issue by tobieche110** [eclipse/windowbuilder#347]
### Discussed in https://github.com/eclipse/windowbuilder/discussions/345

<div type='discussions-op-text'>

<sup>Originally posted by **tobieche110** October 25, 2022</sup>
Hi! So, I recently installed this plugin. I can't manage to get it to work. I can access the Design tab when I create an Application Window class, but if I try to do anything (inserting a button in the window, redimensioning it, anything) I get this error:
![image](https://user-images.githubusercontent.com/15698861/197889993-cf97727f-2a59-4084-89d0-f4fc0904b1e2.png)
(This particularly happens when I try to redimension it)

I've googled the issue a lot and I can't find any solution. At fist I thought it was an error from this specific project, but it happens even on fresh new projects without any other class.

When I try to run the program, the default window opens, and it seems to work, but I still get this problem.

Please help me.

Stack trace:
org.eclipse.wb.internal.core.utils.exception.DesignerException: 205 (Unable to parse source.). java.lang.System.out.println(799); line: 2 The import java.awt.EventQueue is never used
line: 3 The import javax.swing.JFrame is never used
line: 7 The method initialize() from the type VistasAlumno is never used locally
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseStatement(AstParser.java:162)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseExpression(AstParser.java:111)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.replaceExpressionString(AstEditor.java:1085)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.replaceExpression(AstEditor.java:1035)
	at org.eclipse.wb.internal.swing.model.component.top.SwingTopBoundsSupport.setSizeInts(SwingTopBoundsSupport.java:244)
	at org.eclipse.wb.internal.swing.model.component.top.SwingTopBoundsSupport.setSize(SwingTopBoundsSupport.java:87)
	at org.eclipse.wb.core.gef.policy.selection.TopSelectionEditPolicy$1.executeEdit(TopSelectionEditPolicy.java:120)
	at org.eclipse.wb.core.gef.command.EditCommand$1.run(EditCommand.java:53)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.core.gef.command.EditCommand.execute(EditCommand.java:50)
	at org.eclipse.wb.internal.gef.core.EditDomain.executeCommand(EditDomain.java:59)
	at org.eclipse.wb.gef.core.tools.Tool.executeCommand(Tool.java:209)
	at org.eclipse.wb.gef.graphical.tools.ResizeTracker.handleButtonUp(ResizeTracker.java:140)
	at org.eclipse.wb.gef.core.tools.Tool.mouseUp(Tool.java:395)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseUp(SelectionTool.java:251)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseUp(EditDomain.java:255)
	at org.eclipse.wb.internal.gef.graphical.EditEventManager.mouseUp(EditEventManager.java:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy12/jdk.proxy12.$Proxy46.mouseUp(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.wb.internal.core.utils.exception.DesignerException: 205 (Unable to parse source.). package vistas;
import java.awt.EventQueue;
import javax.swing.JFrame;
class VistasAlumno {
javax.swing.JFrame frame=(javax.swing.JFrame) null;
public static void main(String[] args) {}
private void initialize() {}
VistasAlumno(Object __wbp_param) {
super();java.lang.System.out.println(799);}
} line: 2 The import java.awt.EventQueue is never used
line: 3 The import javax.swing.JFrame is never used
line: 7 The method initialize() from the type VistasAlumno is never used locally
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode(AstParser.java:773)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseStatement(AstParser.java:159)
	... 46 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.String[] org.eclipse.jdt.core.dom.IMethodBinding.getParameterNames()'
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerMethodBinding.<init>(DesignerMethodBinding.java:56)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:87)
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerTypeBinding.<init>(DesignerTypeBinding.java:160)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:70)
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerTypeBinding.<init>(DesignerTypeBinding.java:146)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:70)
	at org.eclipse.wb.internal.core.utils.ast.AstParser$3.postVisit(AstParser.java:946)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3183)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:163)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:223)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.copyBindings(AstParser.java:925)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode0(AstParser.java:827)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode(AstParser.java:770)
	... 47 more

Full context stack trace:
org.eclipse.wb.internal.core.utils.exception.DesignerException: 205 (Unable to parse source.). java.lang.System.out.println(799); line: 2 The import java.awt.EventQueue is never used
line: 3 The import javax.swing.JFrame is never used
line: 7 The method initialize() from the type VistasAlumno is never used locally
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseStatement(AstParser.java:162)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseExpression(AstParser.java:111)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.replaceExpressionString(AstEditor.java:1085)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.replaceExpression(AstEditor.java:1035)
	at org.eclipse.wb.internal.swing.model.component.top.SwingTopBoundsSupport.setSizeInts(SwingTopBoundsSupport.java:244)
	at org.eclipse.wb.internal.swing.model.component.top.SwingTopBoundsSupport.setSize(SwingTopBoundsSupport.java:87)
	at org.eclipse.wb.core.gef.policy.selection.TopSelectionEditPolicy$1.executeEdit(TopSelectionEditPolicy.java:120)
	at org.eclipse.wb.core.gef.command.EditCommand$1.run(EditCommand.java:53)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.core.gef.command.EditCommand.execute(EditCommand.java:50)
	at org.eclipse.wb.internal.gef.core.EditDomain.executeCommand(EditDomain.java:59)
	at org.eclipse.wb.gef.core.tools.Tool.executeCommand(Tool.java:209)
	at org.eclipse.wb.gef.graphical.tools.ResizeTracker.handleButtonUp(ResizeTracker.java:140)
	at org.eclipse.wb.gef.core.tools.Tool.mouseUp(Tool.java:395)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseUp(SelectionTool.java:251)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseUp(EditDomain.java:255)
	at org.eclipse.wb.internal.gef.graphical.EditEventManager.mouseUp(EditEventManager.java:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.wb.internal.draw2d.EventManager$1.invoke(EventManager.java:317)
	at jdk.proxy12/jdk.proxy12.$Proxy46.mouseUp(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.wb.internal.core.utils.exception.DesignerException: 205 (Unable to parse source.). package vistas;
import java.awt.EventQueue;
import javax.swing.JFrame;
class VistasAlumno {
javax.swing.JFrame frame=(javax.swing.JFrame) null;
public static void main(String[] args) {}
private void initialize() {}
VistasAlumno(Object __wbp_param) {
super();java.lang.System.out.println(799);}
} line: 2 The import java.awt.EventQueue is never used
line: 3 The import javax.swing.JFrame is never used
line: 7 The method initialize() from the type VistasAlumno is never used locally
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode(AstParser.java:773)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.parseStatement(AstParser.java:159)
	... 46 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.String[] org.eclipse.jdt.core.dom.IMethodBinding.getParameterNames()'
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerMethodBinding.<init>(DesignerMethodBinding.java:56)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:87)
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerTypeBinding.<init>(DesignerTypeBinding.java:160)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:70)
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerTypeBinding.<init>(DesignerTypeBinding.java:146)
	at org.eclipse.wb.internal.core.utils.ast.binding.BindingContext.get(BindingContext.java:70)
	at org.eclipse.wb.internal.core.utils.ast.AstParser$3.postVisit(AstParser.java:946)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3183)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:163)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:223)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3228)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3180)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.copyBindings(AstParser.java:925)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode0(AstParser.java:827)
	at org.eclipse.wb.internal.core.utils.ast.AstParser.findNode(AstParser.java:770)
	... 47 more
</div>

**Comment by Unluckyjoker** [comment]
Same problem here

**Comment by RyukTV** [comment]
Same problem here I try everything but it the same problem

**Comment by kareemz32** [comment]
Anyone figure out how to fix it yet?

**Comment by merks** [comment]
The missing method was added during the 2022-09 release cycle so you'll need to update JDT to the latest release, e.g., from this site:

https://download.eclipse.org/releases/2022-09/

**Comment by tobieche110** [comment]
> The missing method was added during the 2022-09 release cycle so you'll need to update JDT to the latest release, e.g., from this site:
> 
> https://download.eclipse.org/releases/2022-09/

This fix

**Comment by Flare785** [comment]
@tobieche110 Good evening.
I'm having the same problem and I can't figure out how to solve it. I saw that you are from Argentina. I'm from Spain, if you could help me I would be so grateful. We can comunicate via Discord if you want. Thank you.
