### ISSUE TITLE
WindowBuilder: Unhandled event loop exception (NullPointerException) with JDK17

### ISSUE THREAD

**Issue by adidiot** [eclipse/windowbuilder#47]
Hello,
After having installed: Eclipse 4.21, Java 17 support for Eclipse 2021-09 (4.21), Window Builder 1.9.7 from 
https://download.eclipse.org/windowbuilder/lastgoodbuild/

I started Eclipse (with JDK17) and discovered that WB seems not work correctly :

See above the log message:

ENTRY org.eclipse.ui 4 0 2021-09-17 13:45:51.757
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.viewers.ISelectionProvider.addSelectionChangedListener(org.eclipse.jface.viewers.ISelectionChangedListener)" because "this.m_selectionProvider" is null
	at org.eclipse.wb.internal.core.editor.UndoManager.addSelectionListener(UndoManager.java:187)
	at org.eclipse.wb.internal.core.editor.UndoManager.refreshDesignerEditor(UndoManager.java:382)
	at org.eclipse.wb.internal.core.editor.UndoManager.activate(UndoManager.java:90)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState_True(DesignPage.java:263)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleActiveState(DesignPage.java:241)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode.showPage(DefaultMultiMode.java:125)
	at org.eclipse.wb.internal.core.editor.multi.DefaultMultiMode$1.widgetSelected(DefaultMultiMode.java:63)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5884)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1548)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1531)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1310)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1882)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5884)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4576)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

Thanks for your support
Regards
Alex

**Comment by lcaron** [comment]
Hi Alex,

To help us, can you please try to run Eclipse with another JDK ? I want to know if the issue is due to the latest release of Eclipse or due to JDK 17.

**Comment by adidiot** [comment]
Hi Laurent,

Yes, I am almost sure it is due to the JDK17 (JEP 403: Strongly Encapsulate JDK Internals)
It seems **--illegal-access=permit** does not work anymore ...
I tried to add **--add-opens java.base/java.lang=ALL-UNNAMED** to eclipse.ini but without success Eclipse does not start with this JVM argument.

So I created my own script to start Eclipse with **--add-opens java.base/java.lang=ALL-UNNAMED**

> #!/bin/bash
> /jvm/openjdk/jdk-17/bin/java -jar \
> -noverify \
> -Dosgi.requiredJavaVersion=11 \
> -Dosgi.dataAreaRequiresExplicitInit=true \
> -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true \
> -Xms256m \
> -Xmx2048m \
> -Djava.library.path=/usr/lib/x86_64-linux-gnu/jni \
> --add-modules=ALL-SYSTEM \
> --add-opens java.base/java.lang=ALL-UNNAMED \
> /home/didiot/0_eclipse_4.21/eclipse/plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar \
> -showsplash
> 

With this start script : WB works correctly.

Best Regards,
Alex

**Comment by wimjongman** [comment]
Thanks!

**Comment by cleggink** [comment]
What is the correct way to handle this on a Windows 10 machine with Eclipse Version: 2021-12 (4.22.0) Build id: 20211202-1639? I ammended my shortcut to --add-opens java.base/java.lang=ALL-UNNAMED with no result.
